name: CD Pipeline

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      
       - name: Checkout code
         uses: actions/checkout@v4 

       - name: Deploy via SSH
         uses: appleboy/checkout@v4
         with: 
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd ~/springboot-cicd-demo
             helm upgrade springboot springboot-chart
